# Generated by Django 5.1.7 on 2025-05-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershop',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/%Y/%m/%d/', verbose_name='تصویر پروفایل'),
        ),
    ]
