# Generated by Django 5.1.7 on 2025-05-18 15:25

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'slug'], name='shop_catego_name_cfc740_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم محصول')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', ckeditor.fields.RichTextField()),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='وزن محصول')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='قیمت')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف محصول')),
                ('inventory', models.PositiveSmallIntegerField(default=0, verbose_name='موجودی محصول')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد محصول')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت محصول')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='دسته بندی محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام عکس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تصویر')),
                ('image_field', models.ImageField(upload_to='product_images/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='تصویر محصول')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصویرها',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reply', models.BooleanField(default=False, verbose_name='ریپلای شده')),
                ('message', models.TextField(max_length=1000, verbose_name='متن کامنت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد کامنت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی کامنت')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment', to='shop.comment', verbose_name='ریپلای')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product', verbose_name='کامنت محصول')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['name', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('phone', models.IntegerField(verbose_name='تلفن')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان تیکت')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='دپارتمان')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='موضوع تیکت')),
                ('message', models.TextField(max_length=5500, verbose_name='متن تیکت')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته')], default='open', max_length=100, verbose_name='وضعیت تیکت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد تیکت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت تیکت')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
                'ordering': ['phone', '-created'],
                'indexes': [models.Index(fields=['phone', '-created'], name='shop_ticket_phone_1e7d13_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پاسخ به تیکت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پاسخ به تیکت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت پاسخ تیکت')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='shop.ticket', verbose_name='پاسخ تیکت')),
                ('user_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_response', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': 'پاسخ تیکتها',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'id', 'slug'], name='shop_produc_name_a806b5_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created'], name='shop_image_created_9f3f47_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['name', '-created'], name='shop_commen_name_id_a27f38_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketresponse',
            index=models.Index(fields=['-created'], name='shop_ticket_created_6be754_idx'),
        ),
    ]
