# Generated by Django 5.1.7 on 2025-05-18 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='کد تخفیف')),
                ('valid_from', models.DateTimeField(verbose_name='شروع اعتبار')),
                ('valid_to', models.DateTimeField(verbose_name='پایان اعتبار')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='درصد تخفیف')),
                ('active', models.BooleanField(default=False, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیفات',
                'ordering': ['code', 'active'],
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
