# Generated by Django 5.1.7 on 2025-07-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_discountpercentage_orders_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(verbose_name='مبلغ کل هر محصول'),
        ),
    ]
